#include <catch2/catch_test_macros.hpp>
#include "compiler/Compiler.h"

TEST_CASE("compiler exposes one validated pipeline") {
    std::string error;
    auto c = embx::compiler::compileFile("../examples/common.embx", error);
    REQUIRE(c);
    REQUIRE(error.empty());
    REQUIRE(c->ast);
    REQUIRE(c->ir);
    REQUIRE(c->plan);
    REQUIRE(!c->plan->structs.empty());
}

TEST_CASE("compiler facade generates from the same validated plan") {
    std::string error;
    embx::codegen::Output out;
    REQUIRE(embx::compiler::generateCppFile("../examples/common.embx", out, error));
    REQUIRE(error.empty());
    REQUIRE(out.header.find("#pragma once") != std::string::npos);
    REQUIRE(out.source.find("Generated by EmbX") != std::string::npos);
}
