#include "report/FormatReporter.h"
#include "plan/LayoutGraph.h"
#include "reflection/Reflection.h"
#include <sstream>
#include <unordered_map>
namespace embx::report { namespace {
const char* layoutName(reflection::LayoutClass c){switch(c){case reflection::LayoutClass::Exact:return "exact";case reflection::LayoutClass::Bounded:return "bounded";case reflection::LayoutClass::Unbounded:return "unbounded";case reflection::LayoutClass::Unknown:return "unknown";}return "unknown";}
const char* endianName(plan::Endian e){switch(e){case plan::Endian::Little:return "little";case plan::Endian::Big:return "big";case plan::Endian::Native:return "native";}return "unknown";}
void line(std::ostringstream&o,int n,const std::string&s){for(int i=0;i<n;++i)o<<"    ";o<<s<<'\n';}
std::string sizeText(const std::optional<runtime::LayoutSize>&v){return v?std::to_string(*v)+" bytes":"unknown";}
void member(std::ostringstream&o,const reflection::Member&m,int level){std::string s=std::string(reflection::kindName(m.kind))+" "+(m.name.empty()?"<unnamed>":m.name);if(!m.type.empty())s+=" : "+m.type;if(m.kind==reflection::Kind::Field){s+=" offset="+(m.staticOffset?std::to_string(*m.staticOffset)+" bytes":"unknown");s+=" size="+sizeText(m.staticSize);s+=" layout="+std::string(layoutName(m.layoutClass));if(m.bits)s+=" bits="+std::to_string(m.bits);if(m.terminated)s+=" terminated=yes";if(m.maxPayload)s+=" max_payload="+std::to_string(*m.maxPayload)+" bytes";}if(m.kind==reflection::Kind::Callback)s+=" args="+std::to_string(m.callbackArgs.size());line(o,level,s);for(const auto&c:m.nested)member(o,c,level+1);}
}
bool generate(const plan::Module&p,std::string&out,std::string&error){out.clear();error.clear();const auto r=reflection::inspect(p);plan::LayoutGraph g;if(!plan::buildLayoutGraph(p,g,error)){out.clear();return false;}std::unordered_map<std::string,std::size_t> deps;for(const auto&e:g.edges){if(e.from>=g.nodes.size()){error="format reporter: invalid dependency graph source";out.clear();return false;}++deps[g.nodes[e.from].owner];}
std::ostringstream o;o<<"EmbX Format Report\n";line(o,0,"module: <anonymous>");line(o,0,"declarations:");line(o,1,"structs: "+std::to_string(r.structNames.size()));line(o,1,"aliases: "+std::to_string(r.aliasNames.size()));line(o,1,"enums: "+std::to_string(r.enumNames.size()));line(o,1,"constants: "+std::to_string(r.constantNames.size()));line(o,1,"callbacks: "+std::to_string(r.callbackNames.size()));line(o,1,"parameters: "+std::to_string(r.parameters.size()));line(o,0,"structures:");for(const auto&n:r.structNames){auto s=reflection::inspectStruct(p,n);if(!s){error="format reporter: structure disappeared from Plan: "+n;out.clear();return false;}line(o,1,"struct "+s->name);line(o,2,"layout: "+std::string(layoutName(s->layoutClass)));line(o,2,"min_size: "+std::to_string(s->minSize)+" bytes");line(o,2,"max_size: "+sizeText(s->maxSize));line(o,2,"byte_order: "+std::string(endianName(s->endian)));line(o,2,"dependencies: "+std::to_string(deps[s->name]));line(o,2,"alignment: unknown");line(o,2,"members:");for(const auto&m:s->members)member(o,m,3);}for(const auto&p:r.parameters)line(o,0,"parameter "+p.name+" : "+p.type);out=o.str();return true;}
}
